AWSTemplateFormatVersion: 2010-09-09
Description: CF Template para crear Lambda Permission.

Parameters:

  LambdaFunctionArn:
    Type: String
  SourceArn:
    Type: String

Resources:

  # The AWS::Lambda::Permission resource grants an AWS service or another account
  # permission to use a function.

  LambdaPermissions:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !Ref SourceArn
