AWSTemplateFormatVersion: "2010-09-09"
Description: "
  Root cloudformation stack which create:
    - 3 SSSM Enpoint
    - 1 S3 Endpoint Gateway
    - 1 S3 Endpoint Interface
    - 1 VPC Flow Logs
  "

# ==========================================================================
Parameters:
  NamePrefix:
    Type: String
    Description: Name to be used in the resources
    Default: amx-ppl-cc

  TrafficType:
    Description: The type of traffic to log.
    Type: String
    Default: ALL
    AllowedValues:
      - ACCEPT
      - REJECT
      - ALL

  # TAGS Parameters
  Environment:
    Description: "Specify the type of environment with wich to tag your infraestructure resources that support tags."
    Type: String
    AllowedValues:
      - DES
      - Q
      - PD
    Default: DES
    ConstraintDescription: Specify either DES, Q or PD.

# -----------------------------------------------------------------------------
Mappings:
  EnvironmentTranslate:
    DES:
      Environment: des
    Q:
      Environment: q
    PD:
      Environment: pd

# ==========================================================================
Resources:
  EndpointsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "AMX-PPL-CC-VPCE-S3-CF.yaml"
      TimeoutInMinutes: 10
      Parameters:
        VPCID: !ImportValue PPL-CC-VPCID
        VPCCIDR: !ImportValue PPL-CC-VPCCidrBlock
        Environment: !Ref Environment
        PrivateRouteTablesIds: !Join
          - ','
          - - !ImportValue PPL-CC-PrivateRouteTableID
            - !ImportValue PPL-CC-Private2RouteTableID
        PrivateSubnetsIds: !Join
          - ','
          - - !ImportValue PPL-CC-Subnet03ID
            - !ImportValue PPL-CC-Subnet04ID

  FlowLogStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "AMX-PPL-CC-VPCE-FLG-CF.yaml"
      TimeoutInMinutes: 10
      Parameters:
        VPCID: !ImportValue PPL-CC-VPCID
        FLogGroup: !ImportValue ppl-cc-vpce-flogs-lgs-name
        FLogRolArn: !ImportValue ppl-cc-vpce-flogs-lgs-rol-arn
        NamePrefix: !Ref NamePrefix
        TrafficType: !Ref TrafficType
        EnvironmentLower: !FindInMap [EnvironmentTranslate, !Ref Environment, Environment]
