AWSTemplateFormatVersion: "2010-09-09"
Description: "
  Cloudformation stack wich crate:
    - 1 Secret resource with a randomly generated password in its SecretString JSON.
  "

#==========================================================================
Parameters:
  AppPrefix:
    Type: String
    Default: AMX-RTS
  AppPrefixLower:
    Type: String
    Default: amx-rts
  Name:
    Type: String
  PasswordKeyName:
    Type: String
    Default: password
  SecretStringTemplate:
    Type: String
    Default: '{"username": "user"}'
  Description:
    Type: String
    Default: Almacena un secreto para reutilizar

# Secret Parameters
  PasswordLength:
    Type: Number
    Default: 32
  ExcludeCharacters:
    Type: String
    Default: "\"@/\\'"
  ExcludeLowercase:
    Type: String
    Default: false
  ExcludeNumbers:
    Type: String
    Default: false
  ExcludePunctuation:
    Type: String
    Default: false
  ExcludeUppercase:
    Type: String
    Default: false
  IncludeSpace:
    Type: String
    Default: false

  Environment:
    Description: "Specify the type of environment with wich to tag your infraestructure resources that support tags."
    Type: String
    AllowedValues:
      - DES
      - Q
      - PD
    Default: DES
    ConstraintDescription: Specify either DES, Q or PD.

# -----------------------------------------------------------------------------
Mappings:
  EnvironmentToLower:
    DES:
      Environment: des
    Q:
      Environment: q
    PD:
      Environment: pd

#==========================================================================
Resources:
  Secret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${Name}"
      Description: !Ref Description
      KmsKeyId:
        Fn::ImportValue: !Sub
          - "${AppPrefixLower}-${EnvironmentLower}-kms-s3"
          - EnvironmentLower: !FindInMap [EnvironmentToLower, !Ref Environment, Environment]
      GenerateSecretString:
        PasswordLength: !Ref PasswordLength
        ExcludeCharacters: !Ref ExcludeCharacters
        ExcludeLowercase: !Ref ExcludeLowercase
        ExcludeNumbers: !Ref ExcludeNumbers
        ExcludePunctuation: !Ref ExcludePunctuation
        ExcludeUppercase: !Ref ExcludeUppercase
        IncludeSpace: !Ref IncludeSpace
        # GenerateStringKey: !Ref PasswordKeyName
        # SecretStringTemplate: !Ref SecretStringTemplate

      # Los Tags definidos aquí aplican para TODOS los recursos del VPC Stack
      Tags:
        - Key: Name
          Value: !Sub "${AppPrefix}-${Environment}-SM-${Name}"
        - Key: Nombre
          Value: !Sub "${AppPrefix}-${Environment}-SM-${Name}"

#==========================================================================
Outputs:
  SecretArn:
    Description: "Arn of the secret"
    Value: !Ref Secret
    Export:
      Name: !Sub
          - "${AppPrefixLower}-${EnvironmentLower}-secret-arn-${Name}"
          - EnvironmentLower: !FindInMap [EnvironmentToLower, !Ref Environment, Environment]
