template:
  path: APPS/AMX-LMB-PIN-CF-main.yaml
  type: file
parameters:
  AppPrefix: {{environment_variable.AppPrefixUpper}}
  Environment: {{environment_variable.EnvironmentUpper}}
  InstanceName: 'lir'
  ScheduleExpression: 'cron(*/5 * * * ? *)'
  TemplateBucketName: {{environment_variable.S3TemplateBucketName}}
stack_name: {{environment_variable.StackPrefixUpper}}-APP-CF-lir
hooks:
  before_create:
    - !cmd "aws s3api create-bucket --bucket {{environment_variable.S3TemplateBucketName}} --region {{environment_variable.AWS_REGION}}"
    - !cmd "aws s3 cp templates/LAMBDA/AMX-LMB-CF.yaml s3://{{environment_variable.S3TemplateBucketName}}/AMX-LMB-CF.yaml"
    - !cmd "aws s3 cp templates/LAMBDA/AMX-LMB-PRM-SRC-ARN-CF.yaml s3://{{environment_variable.S3TemplateBucketName}}/AMX-LMB-PRM-SRC-ARN-CF.yaml"
    - !cmd "aws s3 cp templates/EBRIDGE/AMX-EBR-SCH-CF.yaml s3://{{environment_variable.S3TemplateBucketName}}/AMX-EBR-SCH-CF.yaml"
  after_create:
    - !cmd "python3 bin/delete_bucket.py {{environment_variable.S3TemplateBucketName}}"
    - !cmd "aws s3 rb s3://{{environment_variable.S3TemplateBucketName}} --force"
  before_update:
    - !cmd "aws s3api create-bucket --bucket {{environment_variable.S3TemplateBucketName}} --region {{environment_variable.AWS_REGION}}"
    - !cmd "aws s3 cp templates/LAMBDA/AMX-LMB-CF.yaml s3://{{environment_variable.S3TemplateBucketName}}/AMX-LMB-CF.yaml"
    - !cmd "aws s3 cp templates/LAMBDA/AMX-LMB-PRM-SRC-ARN-CF.yaml s3://{{environment_variable.S3TemplateBucketName}}/AMX-LMB-PRM-SRC-ARN-CF.yaml"
    - !cmd "aws s3 cp templates/EBRIDGE/AMX-EBR-SCH-CF.yaml s3://{{environment_variable.S3TemplateBucketName}}/AMX-EBR-SCH-CF.yaml"
  after_update:
    - !cmd "python3 bin/delete_bucket.py {{environment_variable.S3TemplateBucketName}}"
    - !cmd "aws s3 rb s3://{{environment_variable.S3TemplateBucketName}} --force"
