template:
  path: S3/AMX-S3-LGS-CF.yaml
  type: file
parameters:
  S3BucketNamePrefix: '{{environment_variable.AppPrefixLower}}'
  Environment: '{{environment_variable.EnvironmentUpper}}'
  InstanceName: 'output'
  ExpirationLogsInDays: '90'
  NoncurrentLogsDays: '1'
stack_name: {{environment_variable.StackPrefixUpper}}-S3-OUT-CF
hooks:
  before_delete:
    - !cmd "BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name {{environment_variable.StackPrefixUpper}}-S3-OUT-CF --query 'Stacks[0].Outputs[?OutputKey==`S3BucketName`].OutputValue' --output text) && python3 bin/delete_bucket.py ${BUCKET_NAME} || true"
    - !cmd "BUCKET_NAME=$(aws cloudformation describe-stacks --stack-name {{environment_variable.StackPrefixUpper}}-S3-OUT-CF --query 'Stacks[0].Outputs[?OutputKey==`LoggingBucketName`].OutputValue' --output text) && python3 bin/delete_bucket.py ${BUCKET_NAME} || true"
